name: Flex
highlighter: rouge
#Google services
google_analytics: UA-91812334-1

#include subfolders to generate pages
include: ['_pages']

markdown: kramdown
#highlighter: pygments

exclude: ['*.Rmd']
encoding: UTF-8